[package]
name = "oombak_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
crossterm = "0.28.1"
ratatui = "0.29.0"
oombak_rs = { version="0.1.0", path="../oombak_rs" }
oombak_gen = { version="0.1.0", path="../oombak_gen" }
